import type { Metadata } from "next";
import { montserrat, notoSansMono } from "@/fonts";

import "./globals.css";

let cssClasses = '';
cssClasses += `${notoSansMono.variable} `;
cssClasses += `${montserrat.variable} `;
cssClasses += `antialiased`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{ children: React.ReactNode; }>;

const RootLayout: React.FC<Props> = (props) => {
  return (
    <html lang="es">
      <body className={cssClasses}>
        {props.children}
      </body>
    </html>
  );
};

export default RootLayout;
